### ISSUE TITLE
Please keep your former projects privately or delete them

### ISSUE THREAD

**Issue by emilygrande** [xorinox/bu#1]
Hi, this is emily, TA for MET CS program. 

Could you please keep your former projects privately or delete them ? I am afraid that someone has used your code for their projects...  

Thanks a lot !

**Comment by ChristopherCanfield** [comment]
Hi Michel,

Please ignore this. This is almost certainly not a legitimate BU request. This person has improperly sent a number of takedown requests to BU students on GitHub. I’ve contacted her via GitHub and BU email, but have not received a response.

I will follow up with the BU MET CS Department tomorrow morning. The department has always been fine with students posting projects to GitHub, and I don’t see any reason for that to have changed.

Christopher Canfield
[BU MET CS Course Facilitator](http://www.bu.edu/phpbin/directory/?index_id=X73432)
